//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Packages/com.moutinhoart.mp_coreutilities/Runtime/Input/IA_Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.moutinhoart.mp_coreutilities/Runtime/Input/IA_Controls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @IA_Controls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @IA_Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""IA_Controls"",
    ""maps"": [
        {
            ""name"": ""CharacterMap"",
            ""id"": ""54715904-8c29-4f71-ae68-0d38d317e0d5"",
            ""actions"": [
                {
                    ""name"": ""IA_Move"",
                    ""type"": ""Value"",
                    ""id"": ""1a9919df-474b-4f3c-91ee-24f0a1ede303"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""IA_Look"",
                    ""type"": ""Value"",
                    ""id"": ""1fed6940-57cb-4656-9061-6f726b3e328b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""IA_Interact"",
                    ""type"": ""Button"",
                    ""id"": ""6a183b84-9626-4893-9d6f-3232ee2e390b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IA_PrimaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""ea8ce4e7-c91a-48e6-a6a4-aa07a5e6d31a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IA_SecondoryAction"",
                    ""type"": ""Button"",
                    ""id"": ""db90922f-105f-4ac5-9971-2ab86fc2252d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""IA_Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f9ad3ac0-1646-4d7b-b9e7-db0abed716be"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bedeeeb0-def9-4c8c-bd85-758096c099de"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IA_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0376365f-1fe5-4f89-8eb4-28db62a530c4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c00aa6fd-dd3a-4bf0-b5c6-227a7644a954"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""50e50b4a-abf7-44ff-8e6c-d60e7d6196e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3267390a-246b-494f-a973-71842ae88798"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""472abf6a-af02-4f42-bef5-50a1341fc759"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IA_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11588fa5-6595-407d-a5bd-66681f535614"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e41303f9-1dbb-4398-a0dc-437eeae338e2"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IA_Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dd2d1a9-2831-4f5a-8bdc-d500aa5df530"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b754e111-3ea2-498d-b175-64dc70d66521"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IA_Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15bb5e86-30c7-4e4a-819d-90595a293a95"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_PrimaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3ba2209-6282-49d6-9f5e-481bead64440"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IA_SecondoryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f6f27d2-d385-4016-8e41-b616cc806fbe"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""IA_Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be3f540c-8bd7-4f83-957b-44c436cbdb51"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""IA_Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // CharacterMap
        m_CharacterMap = asset.FindActionMap("CharacterMap", throwIfNotFound: true);
        m_CharacterMap_IA_Move = m_CharacterMap.FindAction("IA_Move", throwIfNotFound: true);
        m_CharacterMap_IA_Look = m_CharacterMap.FindAction("IA_Look", throwIfNotFound: true);
        m_CharacterMap_IA_Interact = m_CharacterMap.FindAction("IA_Interact", throwIfNotFound: true);
        m_CharacterMap_IA_PrimaryAction = m_CharacterMap.FindAction("IA_PrimaryAction", throwIfNotFound: true);
        m_CharacterMap_IA_SecondoryAction = m_CharacterMap.FindAction("IA_SecondoryAction", throwIfNotFound: true);
        m_CharacterMap_IA_Jump = m_CharacterMap.FindAction("IA_Jump", throwIfNotFound: true);
    }

    ~@IA_Controls()
    {
        UnityEngine.Debug.Assert(!m_CharacterMap.enabled, "This will cause a leak and performance issues, IA_Controls.CharacterMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterMap
    private readonly InputActionMap m_CharacterMap;
    private List<ICharacterMapActions> m_CharacterMapActionsCallbackInterfaces = new List<ICharacterMapActions>();
    private readonly InputAction m_CharacterMap_IA_Move;
    private readonly InputAction m_CharacterMap_IA_Look;
    private readonly InputAction m_CharacterMap_IA_Interact;
    private readonly InputAction m_CharacterMap_IA_PrimaryAction;
    private readonly InputAction m_CharacterMap_IA_SecondoryAction;
    private readonly InputAction m_CharacterMap_IA_Jump;
    /// <summary>
    /// Provides access to input actions defined in input action map "CharacterMap".
    /// </summary>
    public struct CharacterMapActions
    {
        private @IA_Controls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CharacterMapActions(@IA_Controls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CharacterMap/IA_Move".
        /// </summary>
        public InputAction @IA_Move => m_Wrapper.m_CharacterMap_IA_Move;
        /// <summary>
        /// Provides access to the underlying input action "CharacterMap/IA_Look".
        /// </summary>
        public InputAction @IA_Look => m_Wrapper.m_CharacterMap_IA_Look;
        /// <summary>
        /// Provides access to the underlying input action "CharacterMap/IA_Interact".
        /// </summary>
        public InputAction @IA_Interact => m_Wrapper.m_CharacterMap_IA_Interact;
        /// <summary>
        /// Provides access to the underlying input action "CharacterMap/IA_PrimaryAction".
        /// </summary>
        public InputAction @IA_PrimaryAction => m_Wrapper.m_CharacterMap_IA_PrimaryAction;
        /// <summary>
        /// Provides access to the underlying input action "CharacterMap/IA_SecondoryAction".
        /// </summary>
        public InputAction @IA_SecondoryAction => m_Wrapper.m_CharacterMap_IA_SecondoryAction;
        /// <summary>
        /// Provides access to the underlying input action "CharacterMap/IA_Jump".
        /// </summary>
        public InputAction @IA_Jump => m_Wrapper.m_CharacterMap_IA_Jump;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CharacterMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CharacterMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CharacterMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CharacterMapActions" />
        public void AddCallbacks(ICharacterMapActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Add(instance);
            @IA_Move.started += instance.OnIA_Move;
            @IA_Move.performed += instance.OnIA_Move;
            @IA_Move.canceled += instance.OnIA_Move;
            @IA_Look.started += instance.OnIA_Look;
            @IA_Look.performed += instance.OnIA_Look;
            @IA_Look.canceled += instance.OnIA_Look;
            @IA_Interact.started += instance.OnIA_Interact;
            @IA_Interact.performed += instance.OnIA_Interact;
            @IA_Interact.canceled += instance.OnIA_Interact;
            @IA_PrimaryAction.started += instance.OnIA_PrimaryAction;
            @IA_PrimaryAction.performed += instance.OnIA_PrimaryAction;
            @IA_PrimaryAction.canceled += instance.OnIA_PrimaryAction;
            @IA_SecondoryAction.started += instance.OnIA_SecondoryAction;
            @IA_SecondoryAction.performed += instance.OnIA_SecondoryAction;
            @IA_SecondoryAction.canceled += instance.OnIA_SecondoryAction;
            @IA_Jump.started += instance.OnIA_Jump;
            @IA_Jump.performed += instance.OnIA_Jump;
            @IA_Jump.canceled += instance.OnIA_Jump;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CharacterMapActions" />
        private void UnregisterCallbacks(ICharacterMapActions instance)
        {
            @IA_Move.started -= instance.OnIA_Move;
            @IA_Move.performed -= instance.OnIA_Move;
            @IA_Move.canceled -= instance.OnIA_Move;
            @IA_Look.started -= instance.OnIA_Look;
            @IA_Look.performed -= instance.OnIA_Look;
            @IA_Look.canceled -= instance.OnIA_Look;
            @IA_Interact.started -= instance.OnIA_Interact;
            @IA_Interact.performed -= instance.OnIA_Interact;
            @IA_Interact.canceled -= instance.OnIA_Interact;
            @IA_PrimaryAction.started -= instance.OnIA_PrimaryAction;
            @IA_PrimaryAction.performed -= instance.OnIA_PrimaryAction;
            @IA_PrimaryAction.canceled -= instance.OnIA_PrimaryAction;
            @IA_SecondoryAction.started -= instance.OnIA_SecondoryAction;
            @IA_SecondoryAction.performed -= instance.OnIA_SecondoryAction;
            @IA_SecondoryAction.canceled -= instance.OnIA_SecondoryAction;
            @IA_Jump.started -= instance.OnIA_Jump;
            @IA_Jump.performed -= instance.OnIA_Jump;
            @IA_Jump.canceled -= instance.OnIA_Jump;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CharacterMapActions.UnregisterCallbacks(ICharacterMapActions)" />.
        /// </summary>
        /// <seealso cref="CharacterMapActions.UnregisterCallbacks(ICharacterMapActions)" />
        public void RemoveCallbacks(ICharacterMapActions instance)
        {
            if (m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CharacterMapActions.AddCallbacks(ICharacterMapActions)" />
        /// <seealso cref="CharacterMapActions.RemoveCallbacks(ICharacterMapActions)" />
        /// <seealso cref="CharacterMapActions.UnregisterCallbacks(ICharacterMapActions)" />
        public void SetCallbacks(ICharacterMapActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CharacterMapActions" /> instance referencing this action map.
    /// </summary>
    public CharacterMapActions @CharacterMap => new CharacterMapActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CharacterMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CharacterMapActions.AddCallbacks(ICharacterMapActions)" />
    /// <seealso cref="CharacterMapActions.RemoveCallbacks(ICharacterMapActions)" />
    public interface ICharacterMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "IA_Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIA_Move(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IA_Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIA_Look(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IA_Interact" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIA_Interact(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IA_PrimaryAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIA_PrimaryAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IA_SecondoryAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIA_SecondoryAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "IA_Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnIA_Jump(InputAction.CallbackContext context);
    }
}
